"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const userController_1 = require("../Controllers/userController");
;
const router = (0, express_1.Router)();
router.get('/all', userController_1.getAllUsers);
router.post('/new', userController_1.creatingNewUsers);
router.post("/login", userController_1.loginUser);
router.put('/remove/:U_Id', userController_1.removingUser);
exports.default = router;
